linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  unparam:
    check-exported: false
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
        ignored-numbers: 1,2,3,5,10,60,64,100,600,0755,0644,0666

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocheckcompilerdirectives
    - gocyclo
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gosimple
    - govet
    - grouper
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - noctx
    - prealloc
    - promlinter
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - errcheck
        - goconst

run:
  timeout: 5m
  skip-dirs:
    - vendor
