linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocyclo:
    min-complexity: 15
  unparam:
    check-exported: false
  revive:
    enable-all-rules: true
    rules:
      - name: unhandled-error
        disabled: true
      - name: unexported-return
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: add-constant
        disabled: true
      - name:  cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
      - name:  unchecked-type-assertion
        disabled: true
      - name: get-return
        disabled: true
      - name: function-length
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: bare-return
        disabled: true
      - name: import-alias-naming
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: receiver-naming
        disabled: true
      - name: var-naming
        disabled: true
      - name: confusing-results
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: deep-exit
        disabled: true
      - name: modifies-value-receiver
        disabled: true
      - name: exported
        disabled: true
      - name: unnecessary-stmt
        disabled: true
  mnd:
    checks:
    - argument
    - case
    - condition
    - return
    ignored-numbers:
    - '1'
    - '2'
    - '3'
    - '5'
    - '10'
    - '30'
    - '60'
    - '64'
    - '100'
    - '600'
    - '0755'
    - '0644'
    - '0666'
    - '0o666'
    - '0o644'
    - '0o755'
  wsl:
    strict-append: false

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocyclo
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - mnd
    - nilerr
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - notifier/registrator.go
  exclude-rules:
    - path-except: 'api/*/*'
      linters:
        - wsl
    - path: _test\.go
      linters:
        - contextcheck
        - mnd
        - err113
        - errcheck
        - goconst
        - revive
        - wsl

run:
  timeout: 5m
