FROM golang:1.25 as builder

COPY go.mod go.sum /go/src/github.com/moira-alert/moira/

WORKDIR /go/src/github.com/moira-alert/moira

RUN go mod download

COPY . /go/src/github.com/moira-alert/moira/

ARG GO_VERSION="GoVersion"
ARG GIT_COMMIT="git_Commit"
ARG MoiraVersion="MoiraVersion"

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.MoiraVersion=${MoiraVersion} -X main.GoVersion=${GO_VERSION} -X main.GitCommit=${GIT_COMMIT}" -o build/checker github.com/moira-alert/moira/cmd/checker


FROM alpine:3.18.0

RUN apk add --no-cache ca-certificates
&& update-ca-certificates
&& addgroup -S moira
&& adduser -S -G moira moira

COPY pkg/checker/checker.yml /etc/moira/checker.yml
COPY --from=builder /go/src/github.com/moira-alert/moira/build/checker /usr/bin/checker

USER moira

ENTRYPOINT ["/usr/bin/checker"]
