package handler

import (
	"net/http"
	"net/http/pprof"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/render"
	metricSource "github.com/moira-alert/moira/metric_source"
	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/moira-alert/moira"
	"github.com/moira-alert/moira/api"
	moiramiddle "github.com/moira-alert/moira/api/middleware"

	_ "github.com/moira-alert/moira/docs" // docs is generated by Swag CLI, you have to import it.
)

var database moira.Database
var searchIndex moira.Searcher

const contactKey moiramiddle.ContextKey = "contact"
const subscriptionKey moiramiddle.ContextKey = "subscription"

// NewHandler creates new api handler request uris based on github.com/go-chi/chi
func NewHandler(db moira.Database, log moira.Logger, index moira.Searcher, config *api.Config, metricSourceProvider *metricSource.SourceProvider, webConfigContent []byte) http.Handler {
	database = db
	searchIndex = index
	router := chi.NewRouter()
	router.Use(render.SetContentType(render.ContentTypeJSON))
	router.Use(moiramiddle.UserContext)
	router.Use(moiramiddle.RequestLogger(log))
	router.Use(middleware.NoCache)

	router.NotFound(notFoundHandler)
	router.MethodNotAllowed(methodNotAllowedHandler)

	//	@title				Moira Alert
	//	@version			master
	//	@description		This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html)
	//	@description		Check us out on [Github](https://github.com/moira-alert) or look up our [guide on getting started with Moira](https://moira.readthedocs.io)
	//	@contact.name		Contact Moira Team
	//	@contact.email		opensource@skbkontur.com
	//	@license.name		MIT
	//	@BasePath			/api
	//
	//	@tag.name			contact
	//	@tag.description	APIs for working with Moira contacts. For more details, see <https://moira.readthedocs.io/en/latest/installation/webhooks_scripts.html#contact/>
	//
	//	@tag.name			config
	//	@tag.description	View Moira's runtime configuration. For more details, see <https://moira.readthedocs.io/en/latest/installation/configuration.html>
	//
	//	@tag.name			event
	//	@tag.description	APIs for interacting with notification events. See <https://moira.readthedocs.io/en/latest/user_guide/trigger_page.html#event-history/> for details
	//
	//	@tag.name			health
	//	@tag.description	interact with Moira states/health status. See <https://moira.readthedocs.io/en/latest/user_guide/selfstate.html#self-state-monitor/> for details
	//
	//	@tag.name			notification
	//	@tag.description	manage notifications that are currently in queue. See <https://moira.readthedocs.io/en/latest/user_guide/hidden_pages.html#notifications/>
	//
	//	@tag.name			pattern
	//	@tag.description	APIs for interacting with graphite patterns in Moira. See <https://moira.readthedocs.io/en/latest/development/architecture.html#pattern/>
	//
	//	@tag.name			subscription
	//	@tag.description	APIs for managing a user's subscription(s). See <https://moira.readthedocs.io/en/latest/development/architecture.html#subscription/> to learn about Moira subscriptions
	//
	//	@tag.name			tag
	//	@tag.description	APIs for managing tags (a grouping of tags and subscriptions). See <https://moira.readthedocs.io/en/latest/user_guide/subscriptions.html#tags/>
	//
	//	@tag.name			trigger
	//	@tag.description	APIs for interacting with Moira triggers. See <https://moira.readthedocs.io/en/latest/development/architecture.html#trigger/> to learn about Triggers
	//
	//	@tag.name			team
	//	@tag.description	APIs for interacting with Moira teams
	//
	//	@tag.name			teamSubscription
	//	@tag.description	APIs for interacting with Moira subscriptions owned by certain team
	//
	//	@tag.name			teamContact
	//	@tag.description	APIs for interacting with Moira contacts owned by certain team
	//
	//	@tag.name			user
	//	@tag.description	APIs for interacting with Moira users
	router.Route("/api", func(router chi.Router) {
		router.Use(moiramiddle.DatabaseContext(database))
		router.Get("/config", getWebConfig(webConfigContent))
		router.Route("/user", user)
		router.With(moiramiddle.Triggers(config.LocalMetricTTL, config.RemoteMetricTTL)).Route("/trigger", triggers(metricSourceProvider, searchIndex))
		router.Route("/tag", tag)
		router.Route("/pattern", pattern)
		router.Route("/event", event)
		router.Route("/subscription", subscription)
		router.Route("/notification", notification)
		router.Route("/health", health)
		router.Route("/teams", teams)
		router.Route("/contact", func(router chi.Router) {
			contact(router)
			contactEvents(router)
		})
		router.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL("/api/swagger/doc.json"),
		))
		router.Route("/debug/pprof", func(router chi.Router) {
			router.Get("/", pprof.Index)
			router.Get("/cmdline", pprof.Cmdline)
			router.Get("/profile", pprof.Profile)
			router.Get("/symbol", pprof.Symbol)
			router.Get("/trace", pprof.Trace)
			router.Post("/symbol", pprof.Symbol)

			router.Get("/heap", pprof.Handler("heap").ServeHTTP)
			router.Get("/allocs", pprof.Handler("allocs").ServeHTTP)
			router.Get("/goroutine", pprof.Handler("goroutine").ServeHTTP)
			router.Get("/mutex", pprof.Handler("mutex").ServeHTTP)
			router.Get("/threadcreate", pprof.Handler("threadcreate").ServeHTTP)
			router.Get("/block", pprof.Handler("block").ServeHTTP)
		})
	})

	if config.EnableCORS {
		return cors.AllowAll().Handler(router)
	}
	return router
}

func notFoundHandler(writer http.ResponseWriter, request *http.Request) {
	writer.Header().Set("X-Content-Type-Options", "nosniff")
	writer.Header().Set("Content-Type", "application/json")
	writer.WriteHeader(http.StatusNotFound)
	render.Render(writer, request, api.ErrNotFound) //nolint
}

func methodNotAllowedHandler(writer http.ResponseWriter, request *http.Request) {
	writer.Header().Set("Content-Type", "application/json")
	writer.WriteHeader(http.StatusMethodNotAllowed)
	render.Render(writer, request, api.ErrMethodNotAllowed) //nolint
}
