definitions:
  api.ErrorResponse:
    properties:
      error:
        description: application-level error message, for debugging
        type: string
      status:
        description: user-level status message
        type: string
    type: object
  dto.Contact:
    properties:
      id:
        type: string
      team_id:
        type: string
      type:
        type: string
      user:
        type: string
      value:
        type: string
    type: object
  dto.ContactList:
    properties:
      list:
        items:
          $ref: '#/definitions/moira.ContactData'
        type: array
    type: object
  moira.ContactData:
    properties:
      id:
        type: string
      team:
        type: string
      type:
        type: string
      user:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
  description: This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html).
    Check us out on [Github](https://github.com/moira-alert) or look up our [guide
    on getting started with Moira](https://moira.readthedocs.io).
  title: Moira Alert
  version: 2.8.2
paths:
  /api/config:
    get:
      description: View Moira's runtime configuration. For more details, see <https://moira.readthedocs.io/en/latest/installation/configuration.html>
      operationId: get-web-config
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get web configuration
      tags:
      - config
  /api/contact:
    get:
      operationId: get-all-contacts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ContactList'
      summary: Gets all Moira contacts
      tags:
      - contact
    put:
      consumes:
      - application/json
      operationId: create-new-contact
      parameters:
      - description: Data of the new contact
        in: body
        name: contact
        required: true
        schema:
          $ref: '#/definitions/dto.Contact'
      produces:
      - application/json
      responses:
        "200":
          description: Created contact
          schema:
            $ref: '#/definitions/dto.Contact'
        "400":
          description: Request error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Render error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Creates a new contact notification for the current user
      tags:
      - contact
  /api/contact/{contactId}:
    put:
      consumes:
      - application/json
      operationId: update-contact
      parameters:
      - description: ID of the contact to update
        in: path
        name: contactId
        required: true
        type: string
      - description: Updated contact data
        in: body
        name: contact
        required: true
        schema:
          $ref: '#/definitions/dto.Contact'
      produces:
      - application/json
      responses:
        "200":
          description: Updated contact
          schema:
            $ref: '#/definitions/dto.Contact'
        "400":
          description: Request error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Contact not found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Render error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Updates an existing notification contact to the values passed in the
        request body
      tags:
      - contact
swagger: "2.0"
