name: Publish docker nightly
on:
  push:
    branches:
      - "master"

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master

      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish docker images
        run: make docker_nightly_images
