name: Validate OpenAPI-v2 on PR

on:
  - pull_request

jobs:
  mergespec:
    name: Validate spec file (OpenAPI-v2)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make install-swag-v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - run: npm install --location=global @openapitools/openapi-generator
      - run: make spec-v2
      - run: make validate-spec-v2
