name: Build v3 openapi

on:
  push:
    branches:
      - master

jobs:
  validate-spec:
    name: Validate spec file
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make install-swag

      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - run: make install-swag-v3
      - run: make spec-v3
      - run: make validate-spec-v3

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: specfile
          path: docs/swagger-v3.yaml
